title: The Microstructure Exchange
site:
  description: Something
  title: The Microstructure Exchange

# theme: jekyll-theme-cayman
github: 
  repository_url: https://github.com/cpfiffer/microstructure.exchange
  repository_name: microstructure.exchange
  owner_url: https://github.com/cpfiffer
  owner_name: Cameron Pfiffer

speaker-info:
  speaker-name: "Chaojun Wang (Wharton)"
  speaker-paper: "China Walls"
  coauthors: "Tomy Lee (Central European University) and Daniel Nathan (Hong Kong Polytechnic University)"
  speaker-date: "March 31, 11 a.m. (New York time)"
  #paper-link: "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5186551"
  paper-link: "papers/ChinaWalls.pdf" # If you have a file instead
  webinar-link: "https://us06web.zoom.us/j/84504721258?pwd=I2cR9GtVjSa0myOQKYdxRTvQ1PHENW.1"
  # discussant: "Michael Noe (Eurex), Amit Goyal (SFI/Lausanne), and Eric Uhlmann (INSEAD)"
  # slides-link: /slides/RobinhoodSlides_TME.pdf
  abstract: "We evaluate the enforcement of information barriers—China Walls—within conglomerates. Our setting is the 25 million trades in 2018–2024 in the Israeli Shekel market, where the SEC tightened the China Walls around dealers from July 2018. Our difference-in-differences design compares the trade volumes and profits of funds that are affiliated with, clients of, or entirely unrelated to a dealer around the days when the dealer is especially likely to hold valuable information. Before July 2018, dealers extensively share information with both their affiliate funds and their clients. After July 2018, the dealers cease sharing information with their affiliate funds, while continuing to do so with their clients unabated. A back-of-the-envelope calculation shows that the China Walls eliminated 86% of profits by the affiliate funds on event days."
